### PR TITLE
Cleaned up code and added documentation

### PR DESCRIPTION
**Pull request by rafaelklaessen**
Cleaned up JavaScript code and added documentation. The menus are now
being loaded from menus.json. Also fixed tabs in main.css and put the
files in the correct folder (JavaScript in js, CSS in css and PDF in
pdf).

### CODE REVIEW

**Comment by varshit97** [comment]
@rafaelklaessen There is a CORS error coming up. Look into it once. :)

**Comment by rafaelklaessen** [comment]
Yes, that's right, I forgot to say. There's an AJAX request to menus.json, but this can't be performed when you're at file:/// because Chrome won't let you (for security reasons). On a webserver it works just fine (I use XAMPP for this).

**Comment by varshit97** [comment]
@rafaelklaessen You can fix the CORS error by adding some code to the JS.
Something like this https://fiddle.sencha.com/#fiddle/kvu

**Comment by rafaelklaessen** [comment]
That solution uses the Ext JS framework. Doing such would require the complete framework and extra code, just for getting it running on your local file system. As said, on a (local) webserver it works just fine.

**Comment by varshit97** [comment]
@rafaelklaessen As of now I do not have a server space to host. I am just hosting the static page.

**Comment by rafaelklaessen** [comment]
Wut, you have it online right? Because there it'll work. If you want to run it local, you can just download xampp, which will deliver you an apache server. Everything in C:/xampp/htdocs will show up on localhost then.
The only reason it doesn't work on your pc is that you're using 'file:///'. And browsers can't access file:/// or anything in the local file system.

I can show you that it's working by uploading it to a shared webhost (probably what you have as well).

**Comment by rafaelklaessen** [comment]
So if you'd upload it to mess.bitballoon.com, it'd work.

**Comment by varshit97** [comment]
@rafaelklaessen Ohh yeah it works. Could you fix the name on the 1st button?
screenshot from 2016-10-30 22-19-43
The button is showing southMessMenu right. Change it to the name South and northMessMenu to North and so on.

**Comment by rafaelklaessen** [comment]
Yes I can, and I'll do that in a next pull request. Can you merge this one first?

**Pull request merged**
