### PR TITLE
Add KadambVegMess from PDF to script.js file

### PR DESCRIPTION
**Pull request by g4b1nagy**
I hope this is what you were looking for.

### CODE REVIEW

**Comment by g4b1nagy** [comment]
#4

**Comment by varshit97** [comment]
@g4b1nagy If you could remove the new line characters(\n) from the strings and replace them with spaces it would be awesome. :)

**Comment by g4b1nagy** [comment]
Sure thing. Updated. Also replaces some instances of "C , A" with "C, A".

**Comment by varshit97** [comment]
@g4b1nagy Looks awesome. Thanks :D

**Pull request merged**
